services:
  shopping-lists:
    build: shopping-lists
    image: shopping-lists
    restart: "no"
    volumes:
      - ./shopping-lists/:/shopping-lists
      - ./shopping-lists-cache/:/shopping-lists-cache
    ports:
      - 7777:7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env
    networks:
      - mynetwork

  database:
    container_name: SSLists-server
    image: postgres:14.1
    restart: "no"
    ports:
    - 5432:5432
    env_file:
      - project.env
    networks:
      - mynetwork

  flyway:
    image: flyway/flyway:9.11.0-alpine
    restart: "no"
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
    networks:
      - mynetwork

  e2e-playwright:
    entrypoint: "/bin/true"
    build: e2e-playwright
    image: e2e-playwright
    depends_on:
      - shopping-lists
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests
    env_file:
      - project.env
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge